import { createFileRoute } from '@tanstack/react-router';
import { Suspense, lazy, useMemo, useState } from 'react';
import { Activity, ArrowDownToLine, Box, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clipboard, Compass, Copy, Crosshair, Gauge, Layers3, Maximize2, Menu, RotateCcw, Ruler, Settings2, ShieldCheck, SlidersHorizontal, TrainFront, TriangleAlert, Wind } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { calculate, portalTypes, roles, soils, spans, windZones, type Alignment, type Category, type Config, type Role, type Soil } from '@/lib/ohe-rules';
import { useOheStore } from '@/lib/ohe-store';

const OheScene = lazy(() => import('@/components/ohe-scene'));
type View = 'iso' | 'front' | 'side';

export const Route = createFileRoute('/')({
  head: () => ({ meta: [
    { title: 'RDSO OHE Mast & Foundation Configurator | Engineering Workspace' },
    { name: 'description', content: 'Explore overhead electrification mast, track geometry, and foundation configurations in an interactive engineering workspace.' },
    { property: 'og:title', content: 'RDSO OHE Mast & Foundation Configurator' },
    { property: 'og:description', content: 'Interactive client-side workspace for overhead electrification mast and foundation configurations.' },
    { property: 'og:type', content: 'website' },
    { name: 'twitter:card', content: 'summary_large_image' },
  ] }),
  component: Configurator,
});

function Label({ children, hint }: { children: React.ReactNode; hint?: string }) {
  return <div className="flex items-center gap-1.5 text-[11px] font-semibold uppercase text-muted-foreground">{children}{hint && <Tooltip><TooltipTrigger asChild><CircleHelp className="size-3.5 cursor-help" /></TooltipTrigger><TooltipContent>{hint}</TooltipContent></Tooltip>}</div>;
}
function SectionTitle({ index, title, icon: Icon }: { index: string; title: string; icon: typeof Box }) {
  return <div className="mb-4 flex items-center gap-2.5"><span className="font-mono text-[10px] text-primary">{index}</span><Icon className="size-4 text-muted-foreground" /><h3 className="text-xs font-bold uppercase text-foreground">{title}</h3></div>;
}
function Metric({ label, value, sub, icon: Icon, highlight = false }: { label: string; value: string; sub: string; icon: typeof Box; highlight?: boolean }) {
  return <div className="min-w-0 border-r border-b border-border p-4 last:border-r-0 md:p-5"><div className="mb-4 flex items-center justify-between gap-2"><span className="text-[10px] font-bold uppercase text-muted-foreground">{label}</span><Icon className={`size-4 ${highlight ? 'text-signal' : 'text-primary'}`} /></div><div className={`truncate font-display text-[25px] font-semibold leading-none ${highlight ? 'text-signal' : 'text-foreground'}`} title={value}>{value}</div><div className="mt-2 truncate font-mono text-[10px] text-muted-foreground" title={sub}>{sub}</div></div>;
}
function Configurator() {
  const state = useOheStore();
  const { set, reset, ...config } = state;
  const result = useMemo(() => calculate(config), [config.category, config.wind, config.implantation, config.alignment, config.radius, config.span, config.role, config.soil, config.tracks, config.portalSpan, config.portalType]);
  const [view, setView] = useState<View>('iso');
  const [collapsed, setCollapsed] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<'specifications'|'reference'>('specifications');
  const portal = portalTypes.find(p => p.value === config.portalType) ?? { value: 'N', label: 'N-Type', maxTracks: 4, minSpan: 10, maxSpan: 20.4 };
  const specText = `RDSO OHE MAST & FOUNDATION CONFIGURATION\nStructure: ${result.mast}\nRole: ${config.role}\nWind: ${config.wind} kgf/m² (${result.windBand})\nAlignment: ${config.alignment}${config.alignment !== 'tangent' ? `, radius ${config.radius} m, versine ${result.versine.toFixed(1)} mm` : ''}\nSpan: ${config.span} m\nImplantation: ${config.implantation.toFixed(2)} m\nSoil: ${soils.find(s => s.value === config.soil)?.label}\nIndicative FBM: ${result.fbm}\nIndicative foundation: ${result.foundation}\nFoundation envelope: ${result.a.toFixed(2)} × ${result.b.toFixed(2)} × ${result.h.toFixed(2)} m\nEstimated concrete: ${result.totalVolume.toFixed(2)} m³\n\nPRELIMINARY CONFIGURATION ONLY — verify against current approved RDSO drawings and site calculations.`;
  const copy = async () => { try { await navigator.clipboard.writeText(specText); setCopied(true); window.setTimeout(() => setCopied(false), 2200); } catch { setCopied(false); } };
  const rows = [
    { parameter: 'Wind pressure', value: `${config.wind} kgf/m²`, reference: 'Wind-zone input', limit: `${result.windBand} zone`, good: true },
    { parameter: 'Implantation', value: `${config.implantation.toFixed(2)} m`, reference: 'Setting distance', limit: `≥ ${result.minSetting.toFixed(2)} m`, good: result.settingValid },
    { parameter: 'Track span', value: `${config.span.toFixed(1)} m`, reference: 'Span input', limit: '22.5–72 m', good: true },
    { parameter: 'Curve radius', value: config.alignment === 'tangent' ? 'Straight track' : `${config.radius} m`, reference: 'Alignment input', limit: config.alignment === 'tangent' ? '—' : '200–3500 m', good: true },
    { parameter: 'Versine', value: `${result.versine.toFixed(1)} mm`, reference: 'S² / 8R × 1000', limit: 'Calculated', good: true },
    { parameter: 'Soil bearing capacity', value: `${result.soilCapacity.toLocaleString()} kg/m²`, reference: 'Soil category', limit: 'Site test required', good: true },
    ...(config.category === 'portal' ? [{ parameter: 'Portal envelope', value: `${config.tracks} tracks / ${config.portalSpan.toFixed(1)} m`, reference: `${config.portalType}-Type range`, limit: `${portal.minSpan}–${portal.maxSpan} m / ≤ ${portal.maxTracks} tracks`, good: result.portalValid }] : []),
    { parameter: 'Reverse deflection', value: `${result.reverseDeflection > 0 ? '+' : ''}${result.reverseDeflection} mm`, reference: 'Role allowance', limit: 'Verify on site', good: true },
  ];
  return <TooltipProvider delayDuration={200}><div className="min-h-screen bg-background">
    <header className="no-print relative z-20 flex h-[68px] items-center justify-between border-b border-border bg-panel-deep px-4 lg:px-7">
      <div className="flex min-w-0 items-center gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded bg-primary text-primary-foreground"><TrainFront className="size-5" /></div><div className="min-w-0"><div className="truncate font-display text-[19px] font-semibold uppercase leading-none sm:text-[22px]">RDSO <span className="text-signal">OHE</span> <span className="hidden sm:inline">Configurator</span></div><div className="mt-1.5 hidden font-mono text-[9px] uppercase text-muted-foreground sm:block">Mast & foundation engineering workspace</div></div><div className="ml-2 hidden h-7 w-px bg-border xl:block" /><span className="hidden rounded-sm border border-border px-2 py-1 font-mono text-[9px] text-muted-foreground xl:block">DESIGN TOOL / V1.0</span></div>
      <div className="flex items-center gap-2"><span className="mr-3 hidden items-center gap-2 font-mono text-[10px] text-muted-foreground lg:flex"><span className="size-1.5 rounded-full bg-success" /> LOCAL SESSION</span><Button variant="outline" size="sm" onClick={reset} className="hidden border-border bg-panel text-muted-foreground hover:text-foreground sm:inline-flex"><RotateCcw /> Reset</Button><Button size="sm" onClick={() => window.print()} className="hidden sm:inline-flex"><ArrowDownToLine /> Export sheet</Button><Button variant="outline" size="icon" className="border-border bg-panel lg:hidden" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle controls"><Menu /></Button></div>
    </header>
    <main className="no-print flex min-h-[calc(100vh-68px)] flex-col lg:h-[calc(100vh-68px)] lg:flex-row lg:overflow-hidden">
      <aside className={`${mobileOpen ? 'block' : 'hidden'} ${collapsed ? 'lg:w-[58px]' : 'lg:w-[40%] xl:w-[38%]'} shrink-0 border-b border-border bg-panel lg:block lg:overflow-y-auto lg:border-b-0 lg:border-r` }>
        {collapsed ? <div className="hidden flex-col items-center gap-4 py-5 lg:flex"><Button variant="ghost" size="icon" onClick={() => setCollapsed(false)} title="Expand controls"><ChevronRight /></Button><SlidersHorizontal className="size-4 text-primary" /></div> : <>
          <div className="sticky top-0 z-10 flex items-center justify-between border-b border-border bg-panel px-5 py-4 md:px-7"><div><div className="flex items-center gap-2 text-xs font-bold uppercase"><SlidersHorizontal className="size-4 text-primary" /> Control center</div><div className="mt-1 font-mono text-[10px] text-muted-foreground">CONFIGURATION PARAMETERS</div></div><Button variant="ghost" size="icon" className="hidden lg:inline-flex" onClick={() => setCollapsed(true)} title="Collapse controls"><ChevronLeft /></Button></div>
          <div className="space-y-0 pb-8">
            <section className="border-b border-border px-5 py-5 md:px-7"><SectionTitle index="01" title="Structure category" icon={Layers3} /><div className="grid grid-cols-3 gap-1 rounded bg-panel-deep p-1">{([['single','Single mast'],['ttc','TTC'],['portal','Portal']] as const).map(([value,label]) => <Button key={value} variant={config.category === value ? 'default' : 'ghost'} size="sm" className={`h-9 min-w-0 px-1 text-[11px] ${config.category !== value ? 'text-muted-foreground' : ''}`} onClick={() => set('category',value)}>{label}</Button>)}</div><p className="mt-3 text-[11px] leading-relaxed text-muted-foreground">{config.category === 'single' ? 'Individual support mast with cantilever assembly.' : config.category === 'ttc' ? 'One upright serving a two-track cantilever arrangement.' : 'Cross-track portal structure with paired uprights.'}</p></section>
            <section className="border-b border-border px-5 py-5 md:px-7"><SectionTitle index="02" title="Environmental loads" icon={Wind} /><div className="grid grid-cols-2 gap-4"><div><Label>Wind pressure</Label><Select value={String(config.wind)} onValueChange={v => set('wind', Number(v))}><SelectTrigger className="mt-2 h-10 border-border bg-panel-deep"><SelectValue /></SelectTrigger><SelectContent>{windZones.map(n => <SelectItem key={n} value={String(n)}>{n} kgf/m²</SelectItem>)}</SelectContent></Select></div><div><Label>Soil condition</Label><Select value={config.soil} onValueChange={v => set('soil', v as Soil)}><SelectTrigger className="mt-2 h-10 border-border bg-panel-deep"><SelectValue /></SelectTrigger><SelectContent>{soils.map(s => <SelectItem key={s.value} value={s.value}>{s.label} · {s.capacity.toLocaleString()} kg/m²</SelectItem>)}</SelectContent></Select></div></div><div className="mt-3 flex items-center gap-2 font-mono text-[10px] text-muted-foreground"><span className="size-1.5 rounded-full bg-signal" /> {result.windBand.toUpperCase()} WIND ZONE <span className="ml-auto">{result.soilCapacity.toLocaleString()} kg/m² SBC</span></div></section>
            <section className="border-b border-border px-5 py-5 md:px-7"><SectionTitle index="03" title="Track geometry" icon={Ruler} /><div className="flex items-center justify-between"><Label hint="Horizontal distance between track centre and mast face">Implantation / setting distance</Label><span className="font-mono text-sm font-semibold text-signal">{config.implantation.toFixed(2)} <span className="text-[10px]">m</span></span></div><Slider aria-label="Implantation distance" className="mt-5" min={2.8} max={4.85} step={.05} value={[config.implantation]} onValueChange={v => set('implantation', v[0] ?? 2.8)} /><div className="mt-3 flex items-center justify-between font-mono text-[10px] text-muted-foreground"><span>2.80 m</span><span className="rounded-sm bg-signal-soft px-2 py-1 text-signal">{result.implantationBand}</span><span>4.85 m</span></div>
              <div className="mt-6"><Label>Track alignment</Label><div className="mt-2 grid grid-cols-3 gap-1 rounded bg-panel-deep p-1">{([['tangent','Tangent'],['inside','Inside curve'],['outside','Outside curve']] as const).map(([value,label]) => <Button key={value} size="sm" variant={config.alignment === value ? 'secondary' : 'ghost'} className={`min-w-0 px-1 text-[10px] ${config.alignment !== value ? 'text-muted-foreground' : ''}`} onClick={() => set('alignment',value as Alignment)}>{label}</Button>)}</div></div>
              {config.alignment !== 'tangent' && <div className="mt-5"><div className="flex justify-between"><Label>Curve radius</Label><span className="font-mono text-xs text-foreground">{config.radius} m</span></div><Slider aria-label="Curve radius" className="mt-4" min={200} max={3500} step={50} value={[config.radius]} onValueChange={v => set('radius',v[0] ?? 3500)} /><div className="mt-3 flex justify-between font-mono text-[10px] text-muted-foreground"><span>200 m</span><span>VERSINE {result.versine.toFixed(1)} mm</span><span>3500 m</span></div></div>}
              <div className="mt-6"><Label>OHE span</Label><Select value={String(config.span)} onValueChange={v => set('span', Number(v))}><SelectTrigger className="mt-2 h-10 border-border bg-panel-deep"><SelectValue /></SelectTrigger><SelectContent>{spans.map(s => <SelectItem key={s} value={String(s)}>{s.toFixed(1)} m span</SelectItem>)}</SelectContent></Select></div>
              {config.category === 'portal' && <div className="mt-6 space-y-5 border-t border-border pt-5"><div><Label>Portal type</Label><Select value={config.portalType} onValueChange={v => { set('portalType',v); const p = portalTypes.find(p => p.value === v); if (p) { set('tracks', Math.min(config.tracks,p.maxTracks)); set('portalSpan', Math.max(p.minSpan,Math.min(config.portalSpan,p.maxSpan))); } }}><SelectTrigger className="mt-2 h-10 border-border bg-panel-deep"><SelectValue /></SelectTrigger><SelectContent>{portalTypes.map(p => <SelectItem key={p.value} value={p.value}>{p.label} · up to {p.maxTracks} tracks</SelectItem>)}</SelectContent></Select></div><div className="flex items-center gap-4"><div className="flex-1"><Label>Number of tracks</Label><Select value={String(config.tracks)} onValueChange={v => set('tracks',Number(v))}><SelectTrigger className="mt-2 border-border bg-panel-deep"><SelectValue /></SelectTrigger><SelectContent>{Array.from({length:7},(_,i)=>i+2).map(n=><SelectItem key={n} value={String(n)}>{n} tracks</SelectItem>)}</SelectContent></Select></div><div className="flex-1"><Label>Portal span</Label><span className="mt-2 block font-mono text-sm text-signal">{config.portalSpan.toFixed(1)} m</span></div></div><Slider aria-label="Portal span" min={10} max={36} step={.1} value={[config.portalSpan]} onValueChange={v => set('portalSpan',v[0] ?? 20)} /></div>}
            </section>
            <section className="px-5 py-5 md:px-7"><SectionTitle index="04" title="Mast function" icon={Settings2} /><div className="grid grid-cols-2 gap-2">{roles.map(role => <Button key={role.value} variant="outline" onClick={() => set('role',role.value as Role)} className={`h-auto min-h-[60px] flex-col items-start gap-1 whitespace-normal border px-3 py-2 text-left ${config.role === role.value ? 'border-primary bg-primary/10 text-foreground' : 'border-border bg-panel-deep text-muted-foreground hover:border-input'}`}><span className="flex w-full items-center justify-between text-xs font-bold">{role.label}{config.role === role.value && <Check className="size-3.5 text-primary" />}</span><span className="text-[10px] font-normal opacity-75">{role.detail}</span></Button>)}</div></section>
          </div>
        </>}
      </aside>
      <div className="flex min-w-0 flex-1 flex-col lg:overflow-y-auto">
        <section className="relative flex min-h-[430px] flex-col overflow-hidden border-b border-border bg-panel-deep lg:min-h-[52vh]"><div className="pointer-events-none absolute inset-0 technical-grid opacity-30" />
          <div className="relative z-10 flex flex-wrap items-center justify-between gap-2 border-b border-border/80 bg-panel-deep/85 px-4 py-3 md:px-6"><div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded border border-primary/40 bg-primary/15"><Box className="size-4 text-primary" /></div><div><h2 className="text-xs font-bold uppercase">Interactive structure view</h2><p className="font-mono text-[9px] text-muted-foreground">PROCEDURAL MODEL <span className="mx-1">/</span> {result.mast.toUpperCase()}</p></div></div><div className="flex items-center gap-1 rounded border border-border bg-panel p-1">{([['front','Front'],['side','Side'],['iso','3D view']] as const).map(([v,label]) => <Button key={v} size="sm" variant={view === v ? 'secondary' : 'ghost'} onClick={() => setView(v)} className={`h-7 px-2 text-[10px] ${view !== v ? 'text-muted-foreground' : ''}`}>{label}</Button>)}</div></div>
          <div className="relative min-h-[360px] flex-1"><Suspense fallback={<div className="flex h-full min-h-[360px] items-center justify-center font-mono text-xs text-muted-foreground">Loading structure view…</div>}><OheScene config={config as Config} view={view} /></Suspense><div className="pointer-events-none absolute bottom-4 left-4 flex items-center gap-2 rounded border border-border bg-panel-deep/90 px-3 py-2 font-mono text-[10px] text-foreground"><Crosshair className="size-3.5 text-signal" /> IMPLANTATION <span className="text-signal">{config.implantation.toFixed(2)} m</span></div><div className="pointer-events-none absolute bottom-4 right-4 hidden rounded border border-border bg-panel-deep/85 px-3 py-2 font-mono text-[9px] text-muted-foreground sm:block">DRAG TO ORBIT · SCROLL TO ZOOM</div></div>
        </section>
        <section className="bg-background"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-4 md:px-6"><div><div className="flex items-center gap-2"><Activity className="size-4 text-signal" /><h2 className="font-display text-xl font-semibold uppercase leading-none">Engineering output</h2><span className="rounded-sm border border-signal/30 bg-signal-soft px-2 py-1 font-mono text-[9px] text-signal">PRELIMINARY</span></div><p className="mt-1.5 font-mono text-[10px] text-muted-foreground">CONFIGURATION SUMMARY / LIVE CALCULATION</p></div><div className="flex gap-2"><Button variant="outline" size="sm" className="border-border bg-panel" onClick={copy}>{copied ? <Check /> : <Copy />}{copied ? 'Copied' : 'Copy spec'}</Button><Button size="sm" className="sm:hidden" onClick={() => window.print()}><ArrowDownToLine /></Button></div></div>
          <div className="grid grid-cols-2 border-b border-border bg-panel-deep md:grid-cols-4"><Metric label="Selected structure" value={result.mast} sub={config.role + ' / ' + result.windBand + ' wind'} icon={Layers3} /><Metric label="Foundation code" value={result.foundation} sub={`INDICATIVE · FBM ${result.fbm}`} icon={Box} highlight /><Metric label="Foundation envelope" value={`${result.a.toFixed(1)} × ${result.b.toFixed(1)} × ${result.h.toFixed(1)}`} sub="L × W × D / METRES" icon={Maximize2} /><Metric label="Concrete estimate" value={`${result.totalVolume.toFixed(2)} m³`} sub={`${result.baseVolume.toFixed(2)} BASE + ${result.muffVolume.toFixed(2)} MUFF`} icon={Gauge} /></div>
          {(!result.settingValid || !result.portalValid) && <div className="flex items-start gap-2 border-b border-signal/30 bg-signal-soft px-5 py-3 text-xs text-signal"><TriangleAlert className="mt-0.5 size-4 shrink-0" /><span>{!result.settingValid ? `Setting distance is below the ${result.minSetting.toFixed(2)} m indicative minimum for this alignment. ` : ''}{!result.portalValid ? `Selected ${portal.label} supports ${portal.minSpan}–${portal.maxSpan} m and up to ${portal.maxTracks} tracks.` : ''}</span></div>}
          <div className="flex gap-6 border-b border-border px-5 md:px-6"><Button variant="ghost" className={`h-11 rounded-none border-b-2 px-0 text-xs ${activeTab === 'specifications' ? 'border-primary text-foreground' : 'border-transparent text-muted-foreground'}`} onClick={() => setActiveTab('specifications')}>Specifications</Button><Button variant="ghost" className={`h-11 rounded-none border-b-2 px-0 text-xs ${activeTab === 'reference' ? 'border-primary text-foreground' : 'border-transparent text-muted-foreground'}`} onClick={() => setActiveTab('reference')}>Calculation notes</Button></div>
          {activeTab === 'specifications' ? <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-[11px]"><thead className="bg-panel-deep font-mono text-[9px] uppercase text-muted-foreground"><tr>{['Parameter','Computed value','Basis / reference','Range / note','Check'].map(h => <th className="px-5 py-3 font-medium md:px-6" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i) => <tr key={r.parameter} className={`border-t border-border ${i%2 ? 'bg-panel-deep/50' : ''}`}><td className="px-5 py-3 font-medium md:px-6">{r.parameter}</td><td className="px-5 py-3 font-mono text-foreground md:px-6">{r.value}</td><td className="px-5 py-3 text-muted-foreground md:px-6">{r.reference}</td><td className="px-5 py-3 text-muted-foreground md:px-6">{r.limit}</td><td className="px-5 py-3 md:px-6"><span className={`rounded-sm px-2 py-1 font-mono text-[9px] ${r.good ? 'bg-success/10 text-success' : 'bg-signal-soft text-signal'}`}>{r.good ? 'IN RANGE' : 'REVIEW'}</span></td></tr>)}</tbody></table></div> : <div className="grid gap-4 p-5 text-xs text-muted-foreground md:grid-cols-2 md:p-6"><div className="border-l-2 border-primary pl-4"><div className="mb-1 font-semibold text-foreground">Curve geometry</div>Versine = span² ÷ (8 × radius) × 1000 = <span className="font-mono text-foreground">{result.versine.toFixed(1)} mm</span></div><div className="border-l-2 border-signal pl-4"><div className="mb-1 font-semibold text-foreground">Volume estimate</div>Block envelope ({result.a} × {result.b} × {result.h}) + muff ({result.muffVolume.toFixed(2)} m³) = <span className="font-mono text-foreground">{result.totalVolume.toFixed(2)} m³</span></div><div className="border-l-2 border-border pl-4"><div className="mb-1 font-semibold text-foreground">Reverse deflection</div><span className="font-mono text-foreground">{result.reverseDeflection > 0 ? '+' : ''}{result.reverseDeflection} mm</span> · positive away from track</div><div className="border-l-2 border-border pl-4"><div className="mb-1 font-semibold text-foreground">Foundation selection</div>Indicative mapping from wind, implantation, alignment, structure and soil. Not a certified drawing lookup.</div></div>}
          <div className="flex items-start gap-2 border-t border-border px-5 py-4 text-[11px] leading-relaxed text-muted-foreground md:px-6"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-signal" /><p><strong className="text-foreground">Engineering review required.</strong> Foundation codes and dimensions shown here are indicative frontend estimates, not verified RDSO schedule selections. Confirm current approved drawings, loading, soil tests and site conditions before construction.</p></div>
        </section>
      </div>
    </main>
    <div className="print-sheet hidden"><h1>RDSO OHE Mast & Foundation — Preliminary Configuration Sheet</h1><p>Engineering review required: indicative output, not a certified RDSO drawing lookup.</p><pre className="mt-8 whitespace-pre-wrap font-mono text-sm leading-loose">{specText}</pre></div>
  </div></TooltipProvider>;
}
